-- drop table if exists urls;
CREATE TABLE "user" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "EMAIL" TEXT NOT NULL,
    "PASSWORD" TEXT NOT NULL,
    "LOGIN" TEXT NOT NULL,
    "LOKALIZACJA" TEXT NOT NULL,
    "CZY_USPIONY" INTEGER NOT NULL DEFAULT (1),
    "CZY_ZDALNY" INTEGER NOT NULL DEFAULT (0),
    "CZY_PEDAGOG" INTEGER NOT NULL DEFAULT (0)
);
CREATE TABLE "dojo" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "LOKALIZACJA" TEXT NOT NULL,
    "NAZWA" TEXT NOT NULL,
    "IL_MENTOROW" INTEGER NOT NULL DEFAULT (0)
);
CREATE TABLE "sl_umiejetnosci" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "NAZWA" TEXT NOT NULL
);
CREATE TABLE "dojo_user" (
	"DOJO_ID" INTEGER REFERENCES dojo("ID") NOT NULL,
	"USER_ID" INTEGER REFERENCES user("ID") NOT NULL
);
CREATE TABLE "user_umiejetnosc" (
	"USER_ID" INTEGER REFERENCES user("ID") NOT NULL,
	"UMIEJETNOSC_ID" INTEGER REFERENCES sl_umiejetnosci("ID") NOT NULL
);
CREATE TABLE "wiadomosc" (
	"ID" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	"TRESC" TEXT NOT NULL,
	"NADAWCA_ID" INTEGER REFERENCES user("ID") NOT NULL,
	"ODBIORCA_ID" INTEGER REFERENCES user("ID") NOT NULL,
	"CZY_PRZECZYTANY" INTEGER NOT NULL DEFAULT "0",
	"DATA_WYSLANIA" TEXT NOT NULL
);